name: build & test
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  release:
    types: [published, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        command:
          [
            "BUILD_JAVA",
            "BUILD_FRONTEND",
            "BUILD_AIRFLOW_PLUGIN"
          ]
        timezone:
          [
            "UTC",
            "America/New_York",
          ]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: ${{ matrix.timezone }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Gradle build (and test)
        id: gradle_step
        run: |
          if [[ "${{ matrix.command }}" == "BUILD_JAVA" ]]; then
            source ./.github/scripts/java_build_coverage.sh
          elif [[ "${{ matrix.command }}" == "BUILD_FRONTEND" ]]; then
            ./gradlew :datahub-frontend:build :datahub-web-react:build --parallel
            echo "files=$(pwd)" >> $GITHUB_OUTPUT
          else
            ./gradlew :metadata-ingestion-modules:airflow-plugin:build --parallel
            echo "files=$(pwd)" >> $GITHUB_OUTPUT
          fi
        env:
          NODE_OPTIONS: "--max-old-space-size=3072"
      - name: Upload coverage to Codecov
        if: ${{ matrix.command == 'BUILD_JAVA' && matrix.timezone == 'UTC' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: steps.gradle_step.outputs.files
          fail_ci_if_error: false
          flags: java-${{ matrix.command }}
          name: java-${{ matrix.command }}
          verbose: true
      - name: Upload coverage to Codecov
        if: ${{ matrix.command == 'BUILD_AIRFLOW_PLUGIN' && matrix.timezone == 'UTC' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: steps.gradle_step.outputs.files
          fail_ci_if_error: false
          flags: pytest-airflow-${{ matrix.command }}
          name: pytest-airflow-${{ matrix.command }}
          verbose: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results (build)
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
            **/junit.*.xml
      - name: Ensure codegen is updated
        uses: ./.github/actions/ensure-codegen-updated
      - name: Slack failure notification
        if: failure() && github.event_name == 'push'
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: github-activities

  quickstart-compose-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Download YQ
        uses: chrisdickinson/setup-yq@v1.0.1
        with:
          yq-version: v4.28.2
      - name: Quickstart Compose Validation
        run: ./docker/quickstart/generate_and_compare.sh

  event-file:
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
